import React from 'react'
import { Link } from 'gatsby'
import { StaticImage } from 'gatsby-plugin-image'

export const sliderImages = [
  <StaticImage
    src="../../../assets/uploads/orchestralaptop1.png"
    alt="Client engagement tools"
    placeholder="blurred"
    className="slider-image"
    width={650}
  />,
  <StaticImage
    src="../../../assets/uploads/orchestralaptop2.png"
    alt="Client engagement tools"
    placeholder="blurred"
    className="slider-image"
    width={650}
  />,
  <StaticImage
    src="../../../assets/uploads/orchestralaptop3.png"
    alt="Client engagement tools"
    placeholder="blurred"
    className="slider-image"
    width={650}
  />,
  <StaticImage
    src="../../../assets/uploads/orchestralaptop4.png"
    alt="Client engagement tools"
    placeholder="blurred"
    className="slider-image"
    width={650}
  />,
]

export const features = [
  {
    title: 'Workflows',
    description: (
      <ul>
        <li>
          The entire process above is called a <b>workflow</b>, comprised of five component steps.
        </li>
        <li>
          Two of these steps require review, where more experienced experts review the original work
          performed. Custom review policies (e.g., sampled or systematic review) for tasks can be
          easily created in Orchestra.
        </li>
        <li>
          The photo resizing step is a machine step, completed by automation/AI rather than by
          experts.
        </li>
        <li>
          Each step emits a JSON blob with structured data generated by either humans or machines.
        </li>
        <li>
          Steps have access to data emitted by previous steps that they depend on. In the example,
          the copy editor has access to both the story and the resized photos.
        </li>
      </ul>
    ),
    icon: (
      <StaticImage src="../../../assets/uploads/workflow.png" alt="Hierarchical view" width={100} />
    ),
  },
  {
    title: 'Project distribution',
    description: (
      <ul>
        <li>
          <p>
            <b>Projects</b> are a series of interconnected tasks. A project is an instance of a
            workflow; a task is an instance of a step.
          </p>
          <ul>
            <li>
              Example: An editor with a story about local elections would create an elections
              project, with tasks for a reporter/photographer/copy editor.
            </li>
          </ul>
        </li>
        <li>
          <p>
            <b>Tasks</b> are carried out by an expert or by a machine.
          </p>
          <ul>
            <li>Example: Photographers capture the story.</li>
            <li>Example: Machines resize and recolor the photos.</li>
          </ul>
        </li>
      </ul>
    ),
    icon: (
      <StaticImage
        src="../../../assets/uploads/project-distribution.png"
        alt="Hierarchical view"
        width={100}
      />
    ),
  },
  {
    title: 'Hierarchical view',
    description: (
      <ul>
        <li>
          <b>Core experts</b> do the initial work on a task.
        </li>
        <li>
          <b>Reviewers</b> provide feedback to other experts to make their work even better.
        </li>
        <li>The core expert submits the task when their work is complete.</li>
        <li>
          The reviewer can choose to accept the task, which is either selected for further review or
          marked as complete.
        </li>
        <li>
          They could also choose to return the task, requesting changes from and giving feedback to
          the worker they are reviewing.
        </li>
      </ul>
    ),
    icon: (
      <StaticImage
        src="../../../assets/uploads/hierarchical-view.png"
        alt="Hierarchical view"
        width={100}
      />
    ),
  },
  {
    title: 'Worker certification',
    description: (
      <ul>
        <li>
          <b>Certifications</b> allow experts to work on tasks they're great at.
        </li>
        <li>
          <p>
            Experts can work toward all sorts of certifications, picking up practice tasks to build
            experience.
          </p>
          <ul>
            <li>
              Example: Joseph is a solid reporter but needs a little more practice as a
              photographer—let's give him some simple tasks so he can improve!
            </li>
          </ul>
        </li>
        <li>
          <p>Experts need additional certification to work in a reviewer role.</p>
          <ul>
            <li>
              Example: Amy has been reporting for quite some time and would be great at mentoring
              new reporters.
            </li>
          </ul>
        </li>
      </ul>
    ),
    icon: (
      <StaticImage
        src="../../../assets/uploads/worker-certification.png"
        alt="Worker certification"
        width={100}
      />
    ),
  },
  {
    title: 'StaffBot',
    description: (
      <ul>
        <li>
          <b>StaffBot</b> quickly and easily staffs projects.
        </li>
        <li>It brings a worker on a project in minutes without relying on human support.</li>
        <li>
          Staffing and project coordination that used to take hours are now completed in minutes
          because StaffBot always knows which workers are available.
        </li>
        <li>
          StaffBot either automatically finds workers for a task based on custom logic, or reaches
          out to qualified workers over Slack or email and offers them a task.
        </li>
        <li>Workers can accept or reject a task after reviewing a summary.</li>
      </ul>
    ),
    icon: <StaticImage src="../../../assets/uploads/staff-bot.png" alt="StaffBot" width={100} />,
  },
  {
    title: 'SanityBot',
    description: (
      <ul>
        <li>
          <b>SanityBot</b> periodically monitors the state of a project and alerts team members if
          something seems off.
        </li>
        <li>
          <p>
            It runs sanity checks every few minutes based on various aspects of project status to
            determine what’s on track and what’s at risk.
          </p>
          <ul>
            <li>
              Example: If you’re close to missing a major deadline, SanityBot will alert team
              members via Slack that the project conditions aren’t being met.
            </li>
          </ul>
        </li>
        <li>
          SanityBot can’t solve problems, but it makes it easier to identify them so you can scale
          your attention across more projects.
        </li>
      </ul>
    ),
    icon: <StaticImage src="../../../assets/uploads/sanitybot.png" alt="StaffBot" width={100} />,
  },
  {
    title: 'Nested self-pruning checklists',
    description: (
      <ul>
        <li>
          <b>Checklists</b> reduce mistakes by reminding workers about important to-do items to
          complete a task.
        </li>
        <li>
          <p>
            In these checklists, related items are grouped and hierarchically nested. For each
            project, a checklist self-prunes to remove irrelevant to-do items.
          </p>
          <ul>
            <li>
              Example: B12’s checklist to complete a customer’s website project includes 153 items
              and self-prunes depending on the project type.
            </li>
          </ul>
        </li>
        <li>
          When it’s time for a reviewer to provide feedback, the checklist serves as a natural
          scaffold for that feedback.
        </li>
        <li>
          Reviewers can leave notes on individual checklist items to give specific and thorough
          feedback.
        </li>
        <li>
          The checklist reminds workers of specific feedback to keep in mind for future projects.
        </li>
      </ul>
    ),
    icon: <StaticImage src="../../../assets/uploads/checklist.png" alt="StaffBot" width={100} />,
  },
  {
    title: 'Time tracking',
    description: (
      <ul>
        <li>
          <b>Time tracking</b> helps estimate how long a project or task takes.
        </li>
        <li>
          This feature provides a timer widget that workers can toggle on to track their time spent
          working on a task.
        </li>
        <li>
          Once the worker stops the timer, a time entry is automatically created for the amount of
          time worked. The worker can add a description to specify the task they’re working on.
        </li>
        <li>
          Orchestra’s timecard page shows all time entries for the current work week, grouped by
          date. The worker can edit and manually add time entries.
        </li>
      </ul>
    ),
    icon: (
      <StaticImage src="../../../assets/uploads/time-tracking.png" alt="StaffBot" width={100} />
    ),
  },
]

export const motivation = [
  {
    title: 'Team',
    description: (
      <>
        <p>
          <a target="_blank" href="https://b12.io/" rel="noreferrer">
            B12
          </a>{' '}
          has open-sourced Orchestra as part of our goal to build a brighter future of work.
        </p>
        <p>
          At B12 our mission is to help people do more meaningful work. The rise of automation in
          the workforce is one of the largest challenges society will face in the coming decades.
          B12 looks to use technology and AI as a force for good to build a brighter future of work.
          As a team we strive to create a transparent and collaborative work environment that
          enables us to build the best possible <Link to="/website-editor">products </Link>
          for our customers, including websites and SEO.
        </p>
        <p>
          We started in New York, but are now a fully distributed company with B12ers in Canada,
          Kyrgyzstan, Turkey, many US states, and beyond. We hope you will join us!
        </p>
      </>
    ),
    icon: <StaticImage src="../../../assets/uploads/team.png" alt="StaffBot" width={100} />,
  },
  {
    title: 'Research',
    description: (
      <>
        <p>Orchestra is motivated by years of research into machine-mediated expert teams.</p>
        <p>
          <a
            target="_blank"
            href="http://hci.stanford.edu/publications/2014/flashteams/flashteams-uist2014.pdf"
            rel="noreferrer"
          >
            Flash teams by Retelny et al.
          </a>
          , a study in empowering managers to coordinate interactions between a team of experts
          contributing to a larger project. Review hierarchies work from{' '}
          <a
            target="_blank"
            href="http://www.cs.berkeley.edu/~bjoern/papers/kulkarni-mobileworks-ieee2012.pdf"
            rel="noreferrer"
          >
            Anand Kulkarni et al.
          </a>{' '}
          and{' '}
          <a target="_blank" href="http://marcua.net/papers/vldb2015-argonaut.pdf" rel="noreferrer">
            Daniel Haas et al.
          </a>{' '}
          shows that machines can pair experts with other experts to improve work quality while
          facilitating mentorship.
        </p>
        <p>
          <a href="http://arxiv.org/pdf/cs/9603104v1.pdf" target="_blank" rel="noreferrer">
            Active learning
          </a>
          , or human-in-the-loop machine learning, is the study of how machine learning model
          training can happen in concert with a domain expert completing their work.
        </p>
        <p>
          In 2019,{' '}
          <a href="http://marcua.net/papers/chi2019-critter.pdf" target="_blank" rel="noreferrer">
            Bharadwaj et al. published B12's first paper
          </a>{' '}
          on how we support constrained creativity in Orchestra through Dynamic Checklists,
          automated quality assurance, and contextual reviewer feedback.
        </p>
        <p>
          In 2020,{' '}
          <a href="https://marcua.net/papers/mixtape-cscw2020.pdf" target="_blank" rel="noreferrer">
            {' '}
            Rahman et al. published B12's second paper
          </a>{' '}
          on how we built a mixed-initiative system to combine multiple sources of semi-structured
          information into a single structured action plan.
        </p>
      </>
    ),
    icon: <StaticImage src="../../../assets/uploads/research.png" alt="StaffBot" width={100} />,
  },
]
